[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x4d4d4d"
blue = "0x6796e6"
cyan = "0x0c7d9d"
green = "0xa5c261"
magenta = "0xb267e6"
red = "0xf44747"
white = "0xffffff"
yellow = "0xffd933"

[colors.normal]
black = "0x181818"
blue = "0x4271ae"
cyan = "0x7a9ec2"
green = "0x6a8759"
magenta = "0x9e7bb0"
red = "0xcc8242"
white = "0xcccccc"
yellow = "0xffc66d"

[colors.primary]
background = "0x242424"
foreground = "0xcccccc"
