alias up="sudo apt update && sudo apt upgrade"
alias dirs="dirs -v"
alias cdd="cd ~/Documents/Dev"
alias cp="cp -i"
alias rm="rm -i"
alias mv="mv -i"

alias gs="git status"
alias gl="git log"
alias gd="git diff"
alias ga="git add"
alias gc="git commit -a"
alias gp="git pull"
alias gu="git push"

alias mgd="google-drive-ocamlfuse ~/GoogleDrive/"
