alias up="sudo apt update && sudo apt upgrade"
alias gitup="/mnt/c/Users/Tobias\ Fried/Dropbox/Personal/code/sh/gitup.sh"
alias telegram-cli="~/tg/bin/telegram-cli"
alias dice="/mnt/c/Users/Tobias\ Fried/Dropbox/Personal/code/c/dice"
alias brn="/mnt/c/Users/Tobias\ Fried/Dropbox/Personal/code/sh/brn.sh"
alias dirs="dirs -v"
alias code="cd /mnt/c/Users/Tobias\ Fried/Dropbox/Personal/code"
alias win="cd /mnt/c/Users/Tobias\ Fried/"
alias colors="/mnt/c/Users/Tobias\ Fried/Dropbox/Personal/code/sh/colors2.sh"
alias cp="cp -i"
alias rm="rm -i"
alias mv="mv -i"

export WIN="/mnt/c/Users/Tobias Fried"
